name = "cldcde"
main = "build/serve.js" 
compatibility_date = "2023-12-01"

[env.production]
name = "cldcde"
routes = [
  { pattern = "cldcde.cc/*", zone_name = "cldcde.cc" }
]

[[env.production.kv_namespaces]]
binding = "CLDCDE_CACHE"
id = "cldcde-cache"

[env.production.vars]
ENVIRONMENT = "production"
DOMAIN = "cldcde.cc"
